"""empty message

Revision ID: 527dfb85eeec
Revises: 6ab8ec2e0d4b
Create Date: 2023-01-27 14:22:08.941950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527dfb85eeec'
down_revision = '6ab8ec2e0d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
