"""empty message

Revision ID: ae74d79504aa
Revises: 3298225b2fb3
Create Date: 2023-01-26 14:10:49.136511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae74d79504aa'
down_revision = '3298225b2fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=False),
    sa.Column('capacidad', sa.String(length=250), nullable=False),
    sa.Column('creacion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
